apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # Example gRPC server with /ping endpoint
          image: docker.io/panthuya/grpc-server
          ports:
            - name: grpc
              containerPort: 6565
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: grpc
      port: 6565
      targetPort: 6565
      protocol: TCP
