apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: backend
spec:
  host: backend
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 50
    outlierDetection:
      consecutiveErrors: 3      # older field, supported in all Istio versions
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
