apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: backend-vs
spec:
  hosts:
  - backend
  http:
  - fault:
      abort:
        httpStatus: 503
        percentage:
          value: 50
    route:
    - destination:
        host: backend
        port:
          number: 6565
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: cancelled,unavailable,resource-exhausted
